name: Validate Code Formatting
on: [push]
jobs:
  validate-code-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: yarn
      # This runs the `prettier` binary inside `node_modules/.bin`.
      - run: yarn prettier --check src
